In [1]:
import pandas as pd
import numpy as np
import matplotlib_inline as plt

In [2]:
dados = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv'

df = pd.read_csv(dados, encoding="latin1", sep= ';')

In [3]:
df_furto_celular_cisp = df.groupby('cisp')['roubo_em_coletivo'].sum().reset_index() #reset_index transforma em coluna

df_furto_celular_cisp = df_furto_celular_cisp.sort_values(by='roubo_em_coletivo', ascending=False)

df_furto_celular_cisp

     cisp  roubo_em_coletivo
17     21              12855
52     59              11511
57     64               8761
35     39               7872
25     29               7316
..    ...                ...
118   142                  1
77     92                  0
115   139                  0
129   155                  0
130   156                  0

[138 rows x 2 columns]

In [4]:
df_aaapai_cisp = df.groupby('cisp')['aaapai'].sum().reset_index()

df_aaapai_cisp = df_aaapai_cisp.sort_values(by='aaapai', ascending=False)

df_aaapai_cisp

     cisp  aaapai
104   126  3661.0
8      12  3655.0
10     14  3346.0
65     74  3343.0
12     16  3179.0
..    ...     ...
130   156    18.0
129   155    16.0
131   157    14.0
94    111    13.0
77     92    12.0

[138 rows x 2 columns]

In [5]:
# Usando .loc
df_capital = df.loc[df['munic'] == 'Rio de Janeiro']

# Usando .query() — sintaxe alternativa mais legível
df_capital = df.query("munic == 'Rio de Janeiro'")

# Repetindo o groupby apenas para a capital
df_cisp_capital = df_capital.groupby('cisp')['furto_celular'].sum().reset_index()

df_cisp_capital = df_cisp_capital.sort_values(by='furto_celular', ascending=False)

df_cisp_capital

    cisp  furto_celular
12    16          25709
2      5          24695
10    14          18286
8     12          16929
0      1          15952
5      9          15009
6     10          14571
14    18          14047
1      4          13992
28    32          12623
31    35          12092
15    19           8717
13    17           8491
25    29           8023
38    42           7995
9     13           7532
19    23           7283
11    15           7109
17    21           6932
30    34           6907
33    37           6605
3      6           6526
29    33           6078
18    22           5714
32    36           5555
37    41           5405
16    20           5248
20    24           4673
23    27           4627
24    28           4067
21    25           4005
22    26           4001
40    44           3729
26    30           3726
34    38           3076
35    39           2899
39    43           2833
36    40           2301
27    31           1702
4      7           1578
7     11            402
41    45             73

In [6]:
array_furto = np.array(df_cisp_capital['furto_celular'])
array_furto

array([25709, 24695, 18286, 16929, 15952, 15009, 14571, 14047, 13992,
       12623, 12092,  8717,  8491,  8023,  7995,  7532,  7283,  7109,
        6932,  6907,  6605,  6526,  6078,  5714,  5555,  5405,  5248,
        4673,  4627,  4067,  4005,  4001,  3729,  3726,  3076,  2899,
        2833,  2301,  1702,  1578,   402,    73])

In [7]:
maximo = np.max(array_furto)
minimo = np.min(array_furto)
media = np.mean(array_furto)
mediana = np.median(array_furto)
q1 = np.percentile(array_furto, 25)
q2 = np.percentile(array_furto, 50)
q3 = np.percentile(array_furto, 75)
distancia = (media - mediana) / mediana
amplitude = maximo - minimo

print(f'O valor máixmo é {maximo}')
print(f'O valor mínimo é {minimo}')
print(f'A Média é {media}')
print(f'A Mediana é {mediana}')
print('Q1:', q1)
print('Q2:', q2)
print('Q3:', q3)
print(f"A distância é de: {distancia: .2%}")

O valor máixmo é 25709
O valor mínimo é 73
A Média é 8040.880952380952
A Mediana é 6565.5
Q1: 4002.0
Q2: 6565.5
Q3: 11248.25
A distância é de:  22.47%

In [9]:
# Usando .loc
df_top25 = df_cisp_capital.loc[df_cisp_capital['furto_celular'] > q3]

# Usando .query()
#df_top25 = df_cisp_capital.query('furto_celular > @q3')
print(df_top25)

    cisp  furto_celular
12    16          25709
2      5          24695
10    14          18286
8     12          16929
0      1          15952
5      9          15009
6     10          14571
14    18          14047
1      4          13992
28    32          12623
31    35          12092

In [10]:
# Usando .loc
df_topmenos25 = df_cisp_capital.loc[df_cisp_capital['furto_celular'] < q1]

# Usando .query()
#df_topmenos25 = df_cisp_capital.query('furto_celular < @q3')
print(df_topmenos25)

df_topmenos25 = df_topmenos25.sort_values(by='furto_celular')

df_topmenos25

    cisp  furto_celular
22    26           4001
40    44           3729
26    30           3726
34    38           3076
35    39           2899
39    43           2833
36    40           2301
27    31           1702
4      7           1578
7     11            402
41    45             73

    cisp  furto_celular
41    45             73
7     11            402
4      7           1578
27    31           1702
36    40           2301
39    43           2833
35    39           2899
34    38           3076
26    30           3726
40    44           3729
22    26           4001

In [11]:
df_roubo_veiculo_cisp = df.groupby('cisp')['roubo_veiculo'].sum().reset_index() #reset_index transforma em coluna

df_roubo_veiculo_cisp = df_roubo_veiculo_cisp.sort_values(by='roubo_veiculo', ascending=False)

df_roubo_veiculo_cisp

     cisp  roubo_veiculo
52     59          37511
57     64          32584
35     39          29321
23     27          27710
30     34          27384
..    ...            ...
77     92              8
115   139              7
116   140              7
113   137              6
114   138              2

[138 rows x 2 columns]

In [12]:
array_roubo_veiculo = np.array(df_roubo_veiculo_cisp['roubo_veiculo'])
array_roubo_veiculo

array([37511, 32584, 29321, 27710, 27384, 24731, 20423, 19889, 19687,
       19265, 19195, 18255, 17937, 16579, 16195, 15540, 15139, 14993,
       14768, 14072, 13937, 12750, 12481, 11965, 11896, 10998, 10995,
       10771, 10079,  9153,  9056,  8539,  8523,  8493,  8158,  7808,
        7699,  7370,  7306,  6883,  6438,  5883,  5187,  4688,  4640,
        4133,  4042,  3880,  3685,  3346,  3263,  2973,  2946,  2763,
        2752,  2525,  2205,  2109,  2042,  2018,  1954,  1951,  1937,
        1902,  1490,  1366,  1299,  1275,  1260,  1175,  1060,  1032,
         971,   925,   786,   772,   749,   655,   579,   500,   481,
         447,   440,   407,   345,   333,   321,   313,   313,   312,
         312,   286,   268,   268,   244,   201,   190,   185,   174,
         173,   152,   129,   106,   103,    90,    90,    87,    81,
          65,    64,    64,    59,    58,    49,    48,    47,    43,
          43,    39,    29,    27,    27,    24,    23,    21,    21,
          21,    20,    20,    18,    17,    13,     9,     8,     7,
           7,     6,     2])

In [13]:
maximo = np.max(array_roubo_veiculo)
minimo = np.min(array_roubo_veiculo)
media = np.mean(array_roubo_veiculo)
mediana = np.median(array_roubo_veiculo)
q1 = np.percentile(array_roubo_veiculo, 25)
q2 = np.percentile(array_roubo_veiculo, 50)
q3 = np.percentile(array_roubo_veiculo, 75)


print(f'O valor máixmo é {maximo}')
print(f'O valor mínimo é {minimo}')
print(f'A Média é {media}')
print(f'A Mediana é {mediana}')
print('Q1:', q1)
print('Q2:', q2)
print('Q3:', q3)

O valor máixmo é 37511
O valor mínimo é 2
A Média é 5209.739130434783
A Mediana é 1217.5
Q1: 103.75
Q2: 1217.5
Q3: 8070.5

In [15]:
df_top25_roubo_veiculo = df_roubo_veiculo_cisp.loc[df_roubo_veiculo_cisp['roubo_veiculo'] > q3]

df_top25_roubo_veiculo

    cisp  roubo_veiculo
52    59          37511
57    64          32584
35    39          29321
23    27          27710
30    34          27384
47    54          24731
53    60          20423
34    38          19889
17    21          19687
31    35          19265
36    40          19195
65    74          18255
29    33          17937
25    29          16579
51    58          16195
45    52          15540
18    22          15139
27    31          14993
40    44          14768
63    72          14072
64    73          13937
26    30          12750
50    57          12481
20    24          11965
49    56          11896
21    25          10998
24    28          10995
19    23          10771
66    75          10079
55    62           9153
16    20           9056
69    78           8539
28    32           8523
46    53           8493
62    71           8158