In [ ]:
import pandas as pd
import numpy as np
import matplotlib_inline as plt

In [ ]:
df_2024_01 = pd.read_csv('dados combustivel\Preços semestrais - AUTOMOTIVOS_2024.01.csv',sep=';', decimal=',')
df_2024_02 = pd.read_csv('dados combustivel\Preços semestrais - AUTOMOTIVOS_2024.02.csv',sep=';', decimal=',')
df_2025_01 = pd.read_csv('dados combustivel\Preços semestrais - AUTOMOTIVOS_2025.01.csv',sep=';', decimal=',')
df_2025_02 = pd.read_csv('dados combustivel\Preços semestrais - AUTOMOTIVOS_2025.02.csv',sep=';', decimal=',')

df = pd.concat([df_2024_01, df_2024_02,
                df_2025_01, df_2025_02],
               ignore_index=True)

print(df.shape); display(df.head())
df.head(5)

C:\Users\jonatans.carvalho\AppData\Local\Temp\ipykernel_17912\4076918591.py:3: DtypeWarning: Columns (0: Regiao - Sigla, 1: Estado - Sigla, 2: Municipio, 3: Revenda, 4: CNPJ da Revenda, 5: Nome da Rua, 6: Numero Rua, 7: Complemento, 8: Bairro, 9: Cep, 10: Produto, 11: Data da Coleta, 12: Unidade de Medida, 13: Bandeira) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025_01 = pd.read_csv('dados combustivel\Preços semestrais - AUTOMOTIVOS_2025.01.csv',sep=';', decimal=',')

(1712267, 16)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA,01/01/2024,5.68,NaN,R$ / litro,VIBRA
1,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA ADITIVADA,01/01/2024,5.68,NaN,R$ / litro,VIBRA
2,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,DIESEL S10,01/01/2024,5.93,NaN,R$ / litro,VIBRA
3,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,ETANOL,01/01/2024,3.99,NaN,R$ / litro,VIBRA
4,NE,AL,ARAPIRACA,AUTO POSTO SAO FRANCISCO LTDA,12.706.529/0001-04,RUA SAO FRANCISCO,274,NaN,CENTRO,57300-080,GASOLINA,01/01/2024,5.48,NaN,R$ / litro,VIBRA

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA,01/01/2024,5.68,NaN,R$ / litro,VIBRA
1,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,GASOLINA ADITIVADA,01/01/2024,5.68,NaN,R$ / litro,VIBRA
2,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,DIESEL S10,01/01/2024,5.93,NaN,R$ / litro,VIBRA
3,NE,AL,ARAPIRACA,COMERCIAL DE COMBUSTIVEIS E LUBRIFICANTES VITA...,02.817.655/0001-82,RODOVIA AL-220,1901,NaN,SANTA ESMERALDA,57312-025,ETANOL,01/01/2024,3.99,NaN,R$ / litro,VIBRA
4,NE,AL,ARAPIRACA,AUTO POSTO SAO FRANCISCO LTDA,12.706.529/0001-04,RUA SAO FRANCISCO,274,NaN,CENTRO,57300-080,GASOLINA,01/01/2024,5.48,NaN,R$ / litro,VIBRA

In [ ]:
# exercicio 2
df_gas_rj = df.loc[(df['Estadi - sigla'] == 'RJ') & (df['Produto'] == 'GASOLINA')]

In [ ]:
#depois ele agrupou
#exercicio 2
df_munic_rj_gas = df_gas_rj.groupby('Municipio')['Valor de Venda'].mean().reset_index()

df_munic_rj_gas.sort_values(by='Valor de Venda', ascending=False)
inplace=True

df_munic_rj_gas

In [ ]:
#exercicio 3
df_posto_rj = df_gas_rj.groupby('Revenda')['Valor de Venda'].mean().reset_index()
df_posto_rj.sort_values(by='Valor de Venda', ascending=False,inplace=True)
df_posto_rj

In [ ]:
#outliers
array_posto = np.arry(df_posto_rj['Valor de Venda'])
minimo = np.min (array_posto)
maximo = np.max (array_posto)

In [ ]:
### Um gráfico revela em segundos o que levaria minutos.

In [ ]:
#.loc para os outlayers
df_outlier_posto_rj = df_posto_rj.loc[df_posto_rj['Valor de Venda']]

In [ ]:
#4 exercico   .isin cria lista de dados
df_rj_sp_etanol = df.loc[(df['Etanol -Sigla'].isin('RJ','SP'))] &

In [ ]:
df_munic_rj = df.loc[(df['Municipio']== 'RIO DE JANEIRO') & (df['Produto'] == 'GASOLINA')]
df_munic_rj.head(3)

In [ ]:
#resposta 4
#filtra primeiro depois agrupa 
df_bairro_rj = df_munic_rj.groupby('Bairro')['Valor de Venda'].mean().reset_index()

df_bairro_rj.sort_values(by='Valor de Venda', ascendind=False),inplace=True

df_bairro_rj